services:
  - type: web
    name: whatsapp-ai-bot
    runtime: node
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: GOOGLE_API_KEY
        sync: false
      - key: PORT
        value: 10000
    healthCheckPath: /health
    disk:
      name: whatsapp-data
      mountPath: /opt/render/project/src
      sizeGB: 1
